### ISSUE TITLE
Move Contributing information from README to CONTRIBUTING

### ISSUE THREAD

**Issue by Istar-Eldritch** [repositive/ui-library#17]
( @tombyers @SebastianPlace  )

We should move the contributors guidelines to the CONTRIBUTING.md as stated in the [GH Recommends](https://github.com/blog/1184-contributing-guidelines)

**Comment by tombyers** [comment]
See https://github.com/repositive/report-issues/issues/1014

**Comment by Istar-Eldritch** [comment]
Should we do it as a separate task or not? if not close this issue as duplicate.

On 21 Jun 2017 10:01 am, Tom Byers <notifications@github.com> wrote:

See repositive/report-issues#1014<https://github.com/repositive/report-issues/issues/1014>
